ARG BASE_IMAGE=ghcr.io/comfy-endpoints/comfybase:latest
FROM ${BASE_IMAGE}

ENV PYTHONUNBUFFERED=1
WORKDIR /opt/comfy_endpoints

COPY . /opt/comfy_endpoints
RUN pip install --no-cache-dir -e .
RUN mkdir -p /opt/comfy/custom_nodes \
 && ln -s /opt/comfy_endpoints/comfy_plugin/comfy_endpoints_contract /opt/comfy/custom_nodes/comfy_endpoints_contract

EXPOSE 3000
ENTRYPOINT ["/opt/comfy_endpoints/docker/entrypoint.sh"]
